# Generated by Django 6.0 on 2025-12-20 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 20, 9, 22, 32, 158508, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
