# Generated by Django 6.0 on 2025-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0002_alter_transaction_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
