# Generated by Django 6.0 on 2025-12-23 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0003_alter_transaction_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="objective",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="destiny_account",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="origin_account",
        ),
        migrations.AddField(
            model_name="account",
            name="goal_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="goal_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="destination_account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_accounts",
                to="wimm.account",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="source_account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_accounts",
                to="wimm.account",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="budget_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Objective",
        ),
    ]
