# Generated by Django 6.0 on 2025-12-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0004_remove_account_objective_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="goal_description",
            field=models.TextField(default="some description"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(default="some description"),
            preserve_default=False,
        ),
    ]
