# Generated by Django 6.0 on 2025-12-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0005_alter_account_goal_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="show_on_summary_section",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
