# Generated by Django 6.0 on 2025-12-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0006_account_show_on_summary_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="include_on_total_amount",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
