# Generated by Django 6.0 on 2025-12-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0007_account_include_on_total_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="show_on_summary_section",
            new_name="include_on_summary_section",
        ),
    ]
