# Generated by Django 6.0 on 2025-12-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0010_alter_configuration_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="currency_type",
            field=models.CharField(max_length=3),
        ),
    ]
