# Generated by Django 6.0 on 2025-12-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0011_alter_configuration_currency_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="currency_type",
        ),
        migrations.AddField(
            model_name="configuration",
            name="locale",
            field=models.CharField(default="en-EN", max_length=16),
            preserve_default=False,
        ),
    ]
