# Generated by Django 6.0 on 2025-12-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0012_remove_configuration_currency_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="currency",
            field=models.CharField(default="USD", max_length=4),
            preserve_default=False,
        ),
    ]
