# Generated by Django 6.0 on 2025-12-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0013_configuration_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="currency_display",
            field=models.CharField(default="symbol", verbose_name=16),
            preserve_default=False,
        ),
    ]
