# Generated by Django 6.0.1 on 2026-01-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0015_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="user",
        ),
    ]
