# Generated by Django 6.0.1 on 2026-01-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0017_configuration_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="color",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
