# Generated by Django 6.0 on 2026-02-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wimm", "0018_account_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="budget_percentage",
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
