# Generated by Django 5.2.7 on 2025-11-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
